### ISSUE TITLE
write function to aggregate model similarity metrics across multiple forecasts 

### ISSUE THREAD

**Issue by nickreich** [reichlab/covidHubUtils#239]
This needs a more complete specification, but the rough idea would be to take in a data_frame of forecasts and output a data_frame that contains pairwise average model similarity as calculated by `calc_cramers_dist_one_model_pair()`. Maybe inputs to function could be

- a forecast_data data_frame
- a list of column names to stratify by (options: location, target, horizon, others?)

and output would be a data_frame with following columns

- model1: the first model in a pair
- model2: the second model in a pair
- [location, target, horizon]: columns specified for stratification in input
- n_obs: the number of distances averaged over
- mean_distance: the average cramers distance
- median_distance: the median cramers distance
- sd_distance: the sd of cramers distance

**Comment by jbracher** [comment]
Maybe add placeholders for the decomposition (even though we're not quite there yet on the theoretical level...):
- mean_F_larger: Mean of the contribution due to F implying larger values than G
- mean_G_larger: Mean of the contribution due to G implying larger values than F
- mean_F_dispersed: Mean of the contribution due to F being more dispersed than G
- mean_G_dispersed: Mean of the contribution due to G being more dispersed than F
Feel free to adapt the naming of course.

**Comment by nikosbosse** [comment]
So for compatibility with `scoringutils::eval_forecasts()` the best would be an input that is similar to this `(scoringutils::quantile_example_data)`: 
![image](https://user-images.githubusercontent.com/37978797/121367225-6b467d80-c93a-11eb-83f1-c765828e88cb.png)

and the output is something like this: 
![image](https://user-images.githubusercontent.com/37978797/121367491-a3e65700-c93a-11eb-8ff1-e3a890e6ca75.png)
(`scoringutils::quantile_example_data[!is.na(prediction) & model == "EpiSoon" & value_type == "death_inc_line" & geography == "England"] %>% scoringutils::eval_forecasts()`)

**Comment by elray1** [comment]
@nikosbosse , I was thinking the function would be more comparable with `scoringutils::pairwise_comparison` than `scoringutils::eval_forecasts`, since the function calculates some outputs for each pair of models.  Does this make sense?  If so, is there an easy way to provide an example of output from `pairwise_comparison`?

**Comment by elray1** [comment]
Here is output from `scoringutils::pairwise_comparison`

```
> res
    model compare_against mean_scores_ratio      pval  adj_pval relative_skill scaled_rel_skill
1: model1          model1         1.0000000 1.0000000 1.0000000      0.4780786         1.000000
2: model1          model2         0.5201253 0.2324219 0.4804688      0.4780786         1.000000
3: model1          model3         0.4394309 0.1601562 0.4804688      0.4780786         1.000000
4: model2          model1         1.9226137 0.2324219 0.4804688      0.9191604         1.922614
5: model2          model2         1.0000000 1.0000000 1.0000000      0.9191604         1.922614
6: model2          model3         0.8448559 0.3222656 0.4804688      0.9191604         1.922614
7: model3          model1         2.2756705 0.1601562 0.4804688      1.0879493         2.275670
8: model3          model2         1.1836338 0.3222656 0.4804688      1.0879493         2.275670
9: model3          model3         1.0000000 1.0000000 1.0000000      1.0879493         2.275670
```

**Comment by nikosbosse** [comment]
So my thinking was that it would be easier to use an input that is similar to what eval_forecasts expects (as you would just have a 'true_value' that varies by quantile instead of a fixed one. The pairwise_comparison function expects an input that is essentially an output from eval_forecasts (and then you pick a metric for which you want to do pairwise comparisons). But your right, it would make more sense if the output were closer to what you get from pairwise_comparison. 
I'll post an example input for that function tomorrow and also think about a sensible input format

**Comment by elray1** [comment]
:+1:  Nick, Nutcha, and I just met and we're thinking about this the same way you described here.  Our plan is for the main input to this function to be a data frame of forecasts in the format returned by `covidHubUtils::load_forecasts`.  The output would have column names `model1`, `model2`, whatever other grouping variables the user specifies like `location`, and a column summarizing mean Cramer's distance (realizing we actually talked a little less about those summary columns).

I'd be open to using `model` and `compare_against` instead of `model1` and `model2`...

**Comment by nikosbosse** [comment]
:+1: That seems reasonable. The output from `load_forecasts` is very similar to the input that `eval_forecasts` expects (I think the main difference is column names). 
I like model and compare_against as names in the output, but that's just a minor preference :)
