### ISSUE TITLE
Create testable R function in covidData that: Calls covidData::load_jhu_truth Gets combinations of timezeros and targets - link to current python code in zoltar-truth code

### ISSUE THREAD

**Issue by mzorn-58** [reichlab/covidHubUtils#29]

**Comment by mzorn-58** [comment]
@elray1 Devteam thinks this belongs in covidData.  Does that seem reasonable to you?

**Comment by elray1** [comment]
I think a function like this could either go into covidData (because that is where other functions for dealing with truth data mainly are), or into covidHubUtils (because this function will not be generally useful to anyone outside of covidHub since it's very specialized to getting inputs to Zoltar; this way, covidData has just foundational functionality that may be broadly useful to others). I have no strong preference.

**Comment by mzorn-58** [comment]
@nickreich Can we get your input on this?  @devteam felt that in meeting about truth data last week, a decision was made to put this and issues [https://github.com/reichlab/covidHubUtils/issues/30] and [https://github.com/reichlab/covid19-forecast-hub/issues/1943] into covidData, but Evan has a compelling reason to keep in covidHubUtils.  Any preference on your side?

**Comment by nickreich** [comment]
Minor preference to as @elray1 suggests, leave covidData as a general-purpose utility for accessing covid-related data, and have functions that are specific to the hub go into covidHubUtils.

**Comment by elray1** [comment]
My understanding is that for now, this will calculate truth only for:
- weekly targets (not daily)
- state and national level (not county)
- inc/cum deaths (not cases or hospitalizations)
