### ISSUE TITLE
add all dependencies to package suggests (for example: DT, mockery)

### ISSUE THREAD

**Issue by nickreich** [reichlab/covidHubUtils#404]
This is required for the vignettes to build but currently is not listed as a formal dependency for the package. Note that the R CMD CHECK GitHub action gets around this by [explicitly installing DT](https://github.com/reichlab/covidHubUtils/blob/088d1b3925d3031dc4f691de21101274f44599e4/.github/workflows/r_cmd_check.yaml#L23)!

**Comment by bsweger** [comment]
Another package to add is `mockery`, which is [used in one of the tests](https://github.com/reichlab/covidHubUtils/blob/088d1b3925d3031dc4f691de21101274f44599e4/tests/testthat/test-get_truth.R#L6)

When running the test suite locally, after cloning the repo:

```
── Error ('test-get_truth.R:6:1'): (code run outside of `test_that()`) ─────────
<packageNotFoundError/error/condition>
Error in `library(mockery)`: there is no package called 'mockery'
Backtrace:
    ▆
 1. └─base::library(mockery) at test-get_truth
 ```

Unlike `DT`, mockery isn't being explicitly installed as part of the unit test pipeline either. I believe the only reason the unit tests succeed in github actions is because [`test-get_truth` only runs when `get_truth.R` is updated](https://github.com/reichlab/covidHubUtils/blob/master/.github/workflows/pr_unittest.yaml#L72), which hasn't happened in 2 years.

**Comment by bsweger** [comment]
Closing, as this was resolved in https://github.com/reichlab/covidHubUtils/pull/409 (I used the wrong wording to auto link the ticket)
