### ISSUE TITLE
ensure correct column types for load_latest_forecasts return value

### ISSUE THREAD

**Issue by elray1** [reichlab/covidHubUtils#94]
For example, if a zoltar query returns no results, the value column is a character type.  If this is a problem in zoltr, maybe it should be solved in that package??

```
    load_latest_forecasts(
      last_forecast_date = "2020-11-30",
      models = "IHME-CurveFit",
      forecast_date_window_size = 6,
      locations = "US",
      types = "point",
      targets = "1 wk ahead inc death",
      source = "zoltar")

# A tibble: 0 x 15
# … with 15 variables: model <chr>, timezero <date>, season <chr>, unit <chr>,
#   target <chr>, class <chr>, value <chr>, cat <chr>, prob <chr>,
#   sample <chr>, quantile <dbl>, family <chr>, param1 <chr>, param2 <chr>,
#   param3 <chr>

```

**Comment by matthewcornell** [comment]
`zoltr::do_zoltar_query()` calls `zoltr::job_data()`, which specifies this `col_types` for forecast queries: "cDcccc????d????" as justified here:

    query_type == "forecasts": recall all but the first six columns have types that depend on the target, and can be
                               number, character, Date, or logical, so we use '?':
      model,timezero,season,unit,target,class,value,cat,prob,sample,quantile,family,param1,param2,param3
      c     D        c      c    c      c     ?     ?   ?    ?      ?        ?      ?      ?      ?

`col_types` is passed by `zoltr::get_resource()` to `readr::read_csv()`, which is where the column type choice is being made. Because Zoltar supports multiple target types, we decided to leave it to `readr::read_csv()` to make the best choice based on the data, which is why we pass `?` for that column. I feel like the default type of the `value` column when there are no forecasts is application-specific. Is it difficult to change the `if (nrow(forecast) ==0){` case to warn and then change the column type in the empty dataframe?
